# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AutoListWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AutoListWindow(object):
    def setupUi(self, AutoListWindow):
        AutoListWindow.setObjectName("AutoListWindow")
        AutoListWindow.resize(957, 391)
        self.pushButton_del = QtWidgets.QPushButton(AutoListWindow)
        self.pushButton_del.setGeometry(QtCore.QRect(880, 72, 51, 51))
        self.pushButton_del.setObjectName("pushButton_del")
        self.pushButton_3 = QtWidgets.QPushButton(AutoListWindow)
        self.pushButton_3.setGeometry(QtCore.QRect(820, 132, 51, 51))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(AutoListWindow)
        self.pushButton_4.setGeometry(QtCore.QRect(700, 74, 51, 51))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_checkParam = QtWidgets.QPushButton(AutoListWindow)
        self.pushButton_checkParam.setGeometry(QtCore.QRect(700, 254, 111, 51))
        self.pushButton_checkParam.setObjectName("pushButton_checkParam")
        self.pushButton_5 = QtWidgets.QPushButton(AutoListWindow)
        self.pushButton_5.setGeometry(QtCore.QRect(760, 72, 51, 51))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_2 = QtWidgets.QPushButton(AutoListWindow)
        self.pushButton_2.setGeometry(QtCore.QRect(760, 132, 51, 51))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_pm = QtWidgets.QPushButton(AutoListWindow)
        self.pushButton_pm.setGeometry(QtCore.QRect(760, 192, 51, 51))
        self.pushButton_pm.setObjectName("pushButton_pm")
        self.pushButton_7 = QtWidgets.QPushButton(AutoListWindow)
        self.pushButton_7.setGeometry(QtCore.QRect(700, 14, 51, 51))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_readDB = QtWidgets.QPushButton(AutoListWindow)
        self.pushButton_readDB.setGeometry(QtCore.QRect(700, 312, 111, 51))
        self.pushButton_readDB.setObjectName("pushButton_readDB")
        self.pushButton_6 = QtWidgets.QPushButton(AutoListWindow)
        self.pushButton_6.setGeometry(QtCore.QRect(820, 72, 51, 51))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_setParam = QtWidgets.QPushButton(AutoListWindow)
        self.pushButton_setParam.setGeometry(QtCore.QRect(820, 192, 111, 51))
        self.pushButton_setParam.setObjectName("pushButton_setParam")
        self.pushButton_point = QtWidgets.QPushButton(AutoListWindow)
        self.pushButton_point.setGeometry(QtCore.QRect(880, 132, 51, 51))
        self.pushButton_point.setObjectName("pushButton_point")
        self.pushButton_8 = QtWidgets.QPushButton(AutoListWindow)
        self.pushButton_8.setGeometry(QtCore.QRect(760, 12, 51, 51))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(AutoListWindow)
        self.pushButton_9.setGeometry(QtCore.QRect(820, 12, 51, 51))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_0 = QtWidgets.QPushButton(AutoListWindow)
        self.pushButton_0.setGeometry(QtCore.QRect(700, 194, 51, 51))
        self.pushButton_0.setObjectName("pushButton_0")
        self.pushButton_1 = QtWidgets.QPushButton(AutoListWindow)
        self.pushButton_1.setGeometry(QtCore.QRect(700, 134, 51, 51))
        self.pushButton_1.setObjectName("pushButton_1")
        self.pushButton_return = QtWidgets.QPushButton(AutoListWindow)
        self.pushButton_return.setGeometry(QtCore.QRect(820, 252, 111, 51))
        self.pushButton_return.setObjectName("pushButton_return")
        self.pushButton_back = QtWidgets.QPushButton(AutoListWindow)
        self.pushButton_back.setGeometry(QtCore.QRect(880, 12, 51, 51))
        self.pushButton_back.setObjectName("pushButton_back")
        self.pushButton_saveDB = QtWidgets.QPushButton(AutoListWindow)
        self.pushButton_saveDB.setGeometry(QtCore.QRect(820, 310, 111, 51))
        self.pushButton_saveDB.setObjectName("pushButton_saveDB")
        self.tableView = QtWidgets.QTableView(AutoListWindow)
        self.tableView.setGeometry(QtCore.QRect(20, 10, 641, 301))
        self.tableView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableView.setObjectName("tableView")
        self.textBrowser_fuzzy = QtWidgets.QTextBrowser(AutoListWindow)
        self.textBrowser_fuzzy.setGeometry(QtCore.QRect(240, 330, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.textBrowser_fuzzy.setFont(font)
        self.textBrowser_fuzzy.setReadOnly(False)
        self.textBrowser_fuzzy.setObjectName("textBrowser_fuzzy")
        self.textBrowser_ratio = QtWidgets.QTextBrowser(AutoListWindow)
        self.textBrowser_ratio.setGeometry(QtCore.QRect(350, 330, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.textBrowser_ratio.setFont(font)
        self.textBrowser_ratio.setReadOnly(False)
        self.textBrowser_ratio.setObjectName("textBrowser_ratio")
        self.textBrowser_int = QtWidgets.QTextBrowser(AutoListWindow)
        self.textBrowser_int.setGeometry(QtCore.QRect(460, 330, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.textBrowser_int.setFont(font)
        self.textBrowser_int.setReadOnly(False)
        self.textBrowser_int.setObjectName("textBrowser_int")
        self.textBrowser_power = QtWidgets.QTextBrowser(AutoListWindow)
        self.textBrowser_power.setGeometry(QtCore.QRect(570, 330, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.textBrowser_power.setFont(font)
        self.textBrowser_power.setReadOnly(False)
        self.textBrowser_power.setObjectName("textBrowser_power")
        self.textBrowser_tpSet = QtWidgets.QTextBrowser(AutoListWindow)
        self.textBrowser_tpSet.setGeometry(QtCore.QRect(30, 330, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.textBrowser_tpSet.setFont(font)
        self.textBrowser_tpSet.setReadOnly(False)
        self.textBrowser_tpSet.setObjectName("textBrowser_tpSet")
        self.textBrowser_leadAdjust = QtWidgets.QTextBrowser(AutoListWindow)
        self.textBrowser_leadAdjust.setGeometry(QtCore.QRect(140, 330, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.textBrowser_leadAdjust.setFont(font)
        self.textBrowser_leadAdjust.setReadOnly(False)
        self.textBrowser_leadAdjust.setObjectName("textBrowser_leadAdjust")

        self.retranslateUi(AutoListWindow)
        QtCore.QMetaObject.connectSlotsByName(AutoListWindow)

    def retranslateUi(self, AutoListWindow):
        _translate = QtCore.QCoreApplication.translate
        AutoListWindow.setWindowTitle(_translate("AutoListWindow", "Form"))
        self.pushButton_del.setText(_translate("AutoListWindow", "删除"))
        self.pushButton_3.setText(_translate("AutoListWindow", "3"))
        self.pushButton_4.setText(_translate("AutoListWindow", "4"))
        self.pushButton_checkParam.setText(_translate("AutoListWindow", "查询参数"))
        self.pushButton_5.setText(_translate("AutoListWindow", "5"))
        self.pushButton_2.setText(_translate("AutoListWindow", "2"))
        self.pushButton_pm.setText(_translate("AutoListWindow", "+/-"))
        self.pushButton_7.setText(_translate("AutoListWindow", "7"))
        self.pushButton_readDB.setText(_translate("AutoListWindow", "读取预留参数"))
        self.pushButton_6.setText(_translate("AutoListWindow", "6"))
        self.pushButton_setParam.setText(_translate("AutoListWindow", "更新参数"))
        self.pushButton_point.setText(_translate("AutoListWindow", "."))
        self.pushButton_8.setText(_translate("AutoListWindow", "8"))
        self.pushButton_9.setText(_translate("AutoListWindow", "9"))
        self.pushButton_0.setText(_translate("AutoListWindow", "0"))
        self.pushButton_1.setText(_translate("AutoListWindow", "1"))
        self.pushButton_return.setText(_translate("AutoListWindow", "返回主界面"))
        self.pushButton_back.setText(_translate("AutoListWindow", "<-"))
        self.pushButton_saveDB.setText(_translate("AutoListWindow", "保存预留参数"))
        self.textBrowser_power.setHtml(_translate("AutoListWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))

