# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(691, 428)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_elect = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_elect.setGeometry(QtCore.QRect(410, 160, 111, 41))
        self.pushButton_elect.setCheckable(True)
        self.pushButton_elect.setObjectName("pushButton_elect")
        self.pushButton_dataChk = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_dataChk.setGeometry(QtCore.QRect(410, 220, 111, 41))
        self.pushButton_dataChk.setCheckable(True)
        self.pushButton_dataChk.setObjectName("pushButton_dataChk")
        self.pushButton_tpControl = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_tpControl.setGeometry(QtCore.QRect(410, 280, 111, 41))
        self.pushButton_tpControl.setCheckable(True)
        self.pushButton_tpControl.setObjectName("pushButton_tpControl")
        self.pushButton_cool = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_cool.setGeometry(QtCore.QRect(410, 330, 111, 41))
        self.pushButton_cool.setCheckable(True)
        self.pushButton_cool.setObjectName("pushButton_cool")
        self.pushButton_circle = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_circle.setGeometry(QtCore.QRect(550, 280, 111, 41))
        self.pushButton_circle.setCheckable(True)
        self.pushButton_circle.setObjectName("pushButton_circle")
        self.pushButton_manu = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_manu.setGeometry(QtCore.QRect(550, 220, 111, 41))
        self.pushButton_manu.setCheckable(True)
        self.pushButton_manu.setObjectName("pushButton_manu")
        self.pushButton_auto = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_auto.setGeometry(QtCore.QRect(550, 160, 111, 41))
        self.pushButton_auto.setCheckable(True)
        self.pushButton_auto.setObjectName("pushButton_auto")
        self.pushButton_exit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_exit.setGeometry(QtCore.QRect(550, 330, 111, 41))
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.label_status = QtWidgets.QLabel(self.centralwidget)
        self.label_status.setGeometry(QtCore.QRect(410, 40, 251, 16))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_status.setFont(font)
        self.label_status.setObjectName("label_status")
        self.label_fluc = QtWidgets.QLabel(self.centralwidget)
        self.label_fluc.setGeometry(QtCore.QRect(410, 70, 251, 16))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_fluc.setFont(font)
        self.label_fluc.setObjectName("label_fluc")
        self.label_tempt = QtWidgets.QLabel(self.centralwidget)
        self.label_tempt.setGeometry(QtCore.QRect(50, 50, 251, 51))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(28)
        font.setBold(False)
        font.setWeight(50)
        self.label_tempt.setFont(font)
        self.label_tempt.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_tempt.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_tempt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_tempt.setObjectName("label_tempt")
        self.label_tpSet = QtWidgets.QLabel(self.centralwidget)
        self.label_tpSet.setGeometry(QtCore.QRect(50, 120, 111, 16))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_tpSet.setFont(font)
        self.label_tpSet.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_tpSet.setObjectName("label_tpSet")
        self.label_power = QtWidgets.QLabel(self.centralwidget)
        self.label_power.setGeometry(QtCore.QRect(190, 120, 111, 16))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_power.setFont(font)
        self.label_power.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_power.setObjectName("label_power")
        self.pushButton_curve = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_curve.setGeometry(QtCore.QRect(40, 180, 81, 31))
        self.pushButton_curve.setObjectName("pushButton_curve")
        self.pushButton_param = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_param.setGeometry(QtCore.QRect(140, 180, 81, 31))
        self.pushButton_param.setObjectName("pushButton_param")
        self.pushButton_log = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_log.setGeometry(QtCore.QRect(240, 180, 81, 31))
        self.pushButton_log.setObjectName("pushButton_log")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 691, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_elect.setText(_translate("MainWindow", "总电源"))
        self.pushButton_dataChk.setText(_translate("MainWindow", "数据查询"))
        self.pushButton_tpControl.setText(_translate("MainWindow", "控温"))
        self.pushButton_cool.setText(_translate("MainWindow", "制冷"))
        self.pushButton_circle.setText(_translate("MainWindow", "循环"))
        self.pushButton_manu.setText(_translate("MainWindow", "手动"))
        self.pushButton_auto.setText(_translate("MainWindow", "自动"))
        self.pushButton_exit.setText(_translate("MainWindow", "退出系统"))
        self.label_status.setText(_translate("MainWindow", "系统启动"))
        self.label_fluc.setText(_translate("MainWindow", "温度波动度："))
        self.label_tempt.setText(_translate("MainWindow", "系统启动"))
        self.label_tpSet.setText(_translate("MainWindow", "系统启动"))
        self.label_power.setText(_translate("MainWindow", "系统启动"))
        self.pushButton_curve.setText(_translate("MainWindow", "曲线"))
        self.pushButton_param.setText(_translate("MainWindow", "参数设置"))
        self.pushButton_log.setText(_translate("MainWindow", "操作日志"))
        self.menu.setTitle(_translate("MainWindow", "参数设置"))

