# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ParamSettingWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(487, 370)
        self.pushButton_9 = QtWidgets.QPushButton(Dialog)
        self.pushButton_9.setGeometry(QtCore.QRect(360, 8, 51, 51))
        self.pushButton_9.setObjectName("pushButton_9")
        self.textBrowser_power = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser_power.setGeometry(QtCore.QRect(120, 288, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.textBrowser_power.setFont(font)
        self.textBrowser_power.setObjectName("textBrowser_power")
        self.textBrowser_fuzzy = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser_fuzzy.setGeometry(QtCore.QRect(120, 168, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.textBrowser_fuzzy.setFont(font)
        self.textBrowser_fuzzy.setObjectName("textBrowser_fuzzy")
        self.textBrowser_correct = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser_correct.setGeometry(QtCore.QRect(120, 88, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.textBrowser_correct.setFont(font)
        self.textBrowser_correct.setObjectName("textBrowser_correct")
        self.pushButton_checkParam = QtWidgets.QPushButton(Dialog)
        self.pushButton_checkParam.setGeometry(QtCore.QRect(240, 250, 111, 51))
        self.pushButton_checkParam.setObjectName("pushButton_checkParam")
        self.pushButton_return = QtWidgets.QPushButton(Dialog)
        self.pushButton_return.setGeometry(QtCore.QRect(360, 248, 111, 51))
        self.pushButton_return.setObjectName("pushButton_return")
        self.textBrowser_tpSet = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser_tpSet.setGeometry(QtCore.QRect(120, 48, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.textBrowser_tpSet.setFont(font)
        self.textBrowser_tpSet.setObjectName("textBrowser_tpSet")
        self.textBrowser_int = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser_int.setGeometry(QtCore.QRect(120, 248, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.textBrowser_int.setFont(font)
        self.textBrowser_int.setObjectName("textBrowser_int")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 88, 91, 21))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(20, 298, 91, 21))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(20, 218, 91, 21))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.pushButton_saveDB = QtWidgets.QPushButton(Dialog)
        self.pushButton_saveDB.setGeometry(QtCore.QRect(360, 306, 111, 51))
        self.pushButton_saveDB.setObjectName("pushButton_saveDB")
        self.pushButton_7 = QtWidgets.QPushButton(Dialog)
        self.pushButton_7.setGeometry(QtCore.QRect(240, 10, 51, 51))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_back = QtWidgets.QPushButton(Dialog)
        self.pushButton_back.setGeometry(QtCore.QRect(420, 8, 51, 51))
        self.pushButton_back.setObjectName("pushButton_back")
        self.pushButton_6 = QtWidgets.QPushButton(Dialog)
        self.pushButton_6.setGeometry(QtCore.QRect(360, 68, 51, 51))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_point = QtWidgets.QPushButton(Dialog)
        self.pushButton_point.setGeometry(QtCore.QRect(420, 128, 51, 51))
        self.pushButton_point.setObjectName("pushButton_point")
        self.pushButton_setParam = QtWidgets.QPushButton(Dialog)
        self.pushButton_setParam.setGeometry(QtCore.QRect(360, 188, 111, 51))
        self.pushButton_setParam.setObjectName("pushButton_setParam")
        self.pushButton_readDB = QtWidgets.QPushButton(Dialog)
        self.pushButton_readDB.setGeometry(QtCore.QRect(240, 308, 111, 51))
        self.pushButton_readDB.setObjectName("pushButton_readDB")
        self.textBrowser_leadAdjust = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser_leadAdjust.setGeometry(QtCore.QRect(120, 128, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.textBrowser_leadAdjust.setFont(font)
        self.textBrowser_leadAdjust.setObjectName("textBrowser_leadAdjust")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(20, 248, 91, 21))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.pushButton_4 = QtWidgets.QPushButton(Dialog)
        self.pushButton_4.setGeometry(QtCore.QRect(240, 70, 51, 51))
        self.pushButton_4.setObjectName("pushButton_4")
        self.textBrowser_ratio = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser_ratio.setGeometry(QtCore.QRect(120, 208, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.textBrowser_ratio.setFont(font)
        self.textBrowser_ratio.setObjectName("textBrowser_ratio")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 128, 91, 21))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.pushButton_0 = QtWidgets.QPushButton(Dialog)
        self.pushButton_0.setGeometry(QtCore.QRect(240, 190, 51, 51))
        self.pushButton_0.setObjectName("pushButton_0")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(20, 168, 91, 21))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 48, 91, 21))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(300, 128, 51, 51))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_5 = QtWidgets.QPushButton(Dialog)
        self.pushButton_5.setGeometry(QtCore.QRect(300, 68, 51, 51))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_del = QtWidgets.QPushButton(Dialog)
        self.pushButton_del.setGeometry(QtCore.QRect(420, 68, 51, 51))
        self.pushButton_del.setObjectName("pushButton_del")
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(360, 128, 51, 51))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_pm = QtWidgets.QPushButton(Dialog)
        self.pushButton_pm.setGeometry(QtCore.QRect(300, 188, 51, 51))
        self.pushButton_pm.setObjectName("pushButton_pm")
        self.pushButton_8 = QtWidgets.QPushButton(Dialog)
        self.pushButton_8.setGeometry(QtCore.QRect(300, 8, 51, 51))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_1 = QtWidgets.QPushButton(Dialog)
        self.pushButton_1.setGeometry(QtCore.QRect(240, 130, 51, 51))
        self.pushButton_1.setObjectName("pushButton_1")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton_9.setText(_translate("Dialog", "9"))
        self.pushButton_checkParam.setText(_translate("Dialog", "查询参数"))
        self.pushButton_return.setText(_translate("Dialog", "返回主界面"))
        self.label_2.setText(_translate("Dialog", "温度修正值"))
        self.label_7.setText(_translate("Dialog", "功率系数"))
        self.label_6.setText(_translate("Dialog", "比例系数"))
        self.pushButton_saveDB.setText(_translate("Dialog", "保存预留参数"))
        self.pushButton_7.setText(_translate("Dialog", "7"))
        self.pushButton_back.setText(_translate("Dialog", "<-"))
        self.pushButton_6.setText(_translate("Dialog", "6"))
        self.pushButton_point.setText(_translate("Dialog", "."))
        self.pushButton_setParam.setText(_translate("Dialog", "更新参数"))
        self.pushButton_readDB.setText(_translate("Dialog", "读取预留参数"))
        self.label_4.setText(_translate("Dialog", "积分系数"))
        self.pushButton_4.setText(_translate("Dialog", "4"))
        self.label_3.setText(_translate("Dialog", "超前调整值"))
        self.pushButton_0.setText(_translate("Dialog", "0"))
        self.label_5.setText(_translate("Dialog", "模糊系数"))
        self.label.setText(_translate("Dialog", "温度设定值"))
        self.pushButton_2.setText(_translate("Dialog", "2"))
        self.pushButton_5.setText(_translate("Dialog", "5"))
        self.pushButton_del.setText(_translate("Dialog", "删除"))
        self.pushButton_3.setText(_translate("Dialog", "3"))
        self.pushButton_pm.setText(_translate("Dialog", "+/-"))
        self.pushButton_8.setText(_translate("Dialog", "8"))
        self.pushButton_1.setText(_translate("Dialog", "1"))

