# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ParamSetWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(488, 372)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 50, 91, 21))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(20, 90, 91, 21))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(20, 130, 91, 21))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(20, 250, 91, 21))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(20, 170, 91, 21))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(20, 220, 91, 21))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(20, 300, 91, 21))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.textBrowser_tpSet = QtWidgets.QTextBrowser(Form)
        self.textBrowser_tpSet.setGeometry(QtCore.QRect(120, 50, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.textBrowser_tpSet.setFont(font)
        self.textBrowser_tpSet.setReadOnly(False)
        self.textBrowser_tpSet.setObjectName("textBrowser_tpSet")
        self.textBrowser_correct = QtWidgets.QTextBrowser(Form)
        self.textBrowser_correct.setGeometry(QtCore.QRect(120, 90, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.textBrowser_correct.setFont(font)
        self.textBrowser_correct.setReadOnly(False)
        self.textBrowser_correct.setObjectName("textBrowser_correct")
        self.textBrowser_leadAdjust = QtWidgets.QTextBrowser(Form)
        self.textBrowser_leadAdjust.setGeometry(QtCore.QRect(120, 130, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.textBrowser_leadAdjust.setFont(font)
        self.textBrowser_leadAdjust.setReadOnly(False)
        self.textBrowser_leadAdjust.setObjectName("textBrowser_leadAdjust")
        self.textBrowser_int = QtWidgets.QTextBrowser(Form)
        self.textBrowser_int.setGeometry(QtCore.QRect(120, 250, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.textBrowser_int.setFont(font)
        self.textBrowser_int.setReadOnly(False)
        self.textBrowser_int.setObjectName("textBrowser_int")
        self.textBrowser_ratio = QtWidgets.QTextBrowser(Form)
        self.textBrowser_ratio.setGeometry(QtCore.QRect(120, 210, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.textBrowser_ratio.setFont(font)
        self.textBrowser_ratio.setReadOnly(False)
        self.textBrowser_ratio.setObjectName("textBrowser_ratio")
        self.textBrowser_fuzzy = QtWidgets.QTextBrowser(Form)
        self.textBrowser_fuzzy.setGeometry(QtCore.QRect(120, 170, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.textBrowser_fuzzy.setFont(font)
        self.textBrowser_fuzzy.setReadOnly(False)
        self.textBrowser_fuzzy.setObjectName("textBrowser_fuzzy")
        self.textBrowser_power = QtWidgets.QTextBrowser(Form)
        self.textBrowser_power.setGeometry(QtCore.QRect(120, 290, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.textBrowser_power.setFont(font)
        self.textBrowser_power.setReadOnly(False)
        self.textBrowser_power.setObjectName("textBrowser_power")
        self.pushButton_7 = QtWidgets.QPushButton(Form)
        self.pushButton_7.setGeometry(QtCore.QRect(240, 12, 51, 51))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(Form)
        self.pushButton_8.setGeometry(QtCore.QRect(300, 10, 51, 51))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(Form)
        self.pushButton_9.setGeometry(QtCore.QRect(360, 10, 51, 51))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_back = QtWidgets.QPushButton(Form)
        self.pushButton_back.setGeometry(QtCore.QRect(420, 10, 51, 51))
        self.pushButton_back.setObjectName("pushButton_back")
        self.pushButton_6 = QtWidgets.QPushButton(Form)
        self.pushButton_6.setGeometry(QtCore.QRect(360, 70, 51, 51))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(240, 72, 51, 51))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(Form)
        self.pushButton_5.setGeometry(QtCore.QRect(300, 70, 51, 51))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_del = QtWidgets.QPushButton(Form)
        self.pushButton_del.setGeometry(QtCore.QRect(420, 70, 51, 51))
        self.pushButton_del.setObjectName("pushButton_del")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(360, 130, 51, 51))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_1 = QtWidgets.QPushButton(Form)
        self.pushButton_1.setGeometry(QtCore.QRect(240, 132, 51, 51))
        self.pushButton_1.setObjectName("pushButton_1")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(300, 130, 51, 51))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_point = QtWidgets.QPushButton(Form)
        self.pushButton_point.setGeometry(QtCore.QRect(420, 130, 51, 51))
        self.pushButton_point.setObjectName("pushButton_point")
        self.pushButton_setParam = QtWidgets.QPushButton(Form)
        self.pushButton_setParam.setGeometry(QtCore.QRect(360, 190, 111, 51))
        self.pushButton_setParam.setObjectName("pushButton_setParam")
        self.pushButton_0 = QtWidgets.QPushButton(Form)
        self.pushButton_0.setGeometry(QtCore.QRect(240, 192, 51, 51))
        self.pushButton_0.setObjectName("pushButton_0")
        self.pushButton_pm = QtWidgets.QPushButton(Form)
        self.pushButton_pm.setGeometry(QtCore.QRect(300, 190, 51, 51))
        self.pushButton_pm.setObjectName("pushButton_pm")
        self.pushButton_checkParam = QtWidgets.QPushButton(Form)
        self.pushButton_checkParam.setGeometry(QtCore.QRect(240, 252, 111, 51))
        self.pushButton_checkParam.setObjectName("pushButton_checkParam")
        self.pushButton_return = QtWidgets.QPushButton(Form)
        self.pushButton_return.setGeometry(QtCore.QRect(360, 250, 111, 51))
        self.pushButton_return.setObjectName("pushButton_return")
        self.pushButton_saveDB = QtWidgets.QPushButton(Form)
        self.pushButton_saveDB.setGeometry(QtCore.QRect(360, 308, 111, 51))
        self.pushButton_saveDB.setObjectName("pushButton_saveDB")
        self.pushButton_readDB = QtWidgets.QPushButton(Form)
        self.pushButton_readDB.setGeometry(QtCore.QRect(240, 310, 111, 51))
        self.pushButton_readDB.setObjectName("pushButton_readDB")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(Form)
        self.plainTextEdit.setGeometry(QtCore.QRect(100, 330, 104, 31))
        self.plainTextEdit.setInputMethodHints(QtCore.Qt.ImhNone)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setGeometry(QtCore.QRect(30, 10, 104, 31))
        self.textEdit.setObjectName("textEdit")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "温度设定值"))
        self.label_2.setText(_translate("Form", "温度修正值"))
        self.label_3.setText(_translate("Form", "超前调整值"))
        self.label_4.setText(_translate("Form", "积分系数"))
        self.label_5.setText(_translate("Form", "模糊系数"))
        self.label_6.setText(_translate("Form", "比例系数"))
        self.label_7.setText(_translate("Form", "功率系数"))
        self.textBrowser_power.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.pushButton_7.setText(_translate("Form", "7"))
        self.pushButton_8.setText(_translate("Form", "8"))
        self.pushButton_9.setText(_translate("Form", "9"))
        self.pushButton_back.setText(_translate("Form", "<-"))
        self.pushButton_6.setText(_translate("Form", "6"))
        self.pushButton_4.setText(_translate("Form", "4"))
        self.pushButton_5.setText(_translate("Form", "5"))
        self.pushButton_del.setText(_translate("Form", "删除"))
        self.pushButton_3.setText(_translate("Form", "3"))
        self.pushButton_1.setText(_translate("Form", "1"))
        self.pushButton_2.setText(_translate("Form", "2"))
        self.pushButton_point.setText(_translate("Form", "."))
        self.pushButton_setParam.setText(_translate("Form", "更新参数"))
        self.pushButton_0.setText(_translate("Form", "0"))
        self.pushButton_pm.setText(_translate("Form", "+/-"))
        self.pushButton_checkParam.setText(_translate("Form", "查询参数"))
        self.pushButton_return.setText(_translate("Form", "返回主界面"))
        self.pushButton_saveDB.setText(_translate("Form", "保存预留参数"))
        self.pushButton_readDB.setText(_translate("Form", "读取预留参数"))

